import { useCallback, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { listRecordings } from '../lib/store';
import { NexaRecording } from '../types';

const duration=(ms:number)=>{const s=Math.floor(ms/1000);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
export default function Library(){const[items,setItems]=useState<NexaRecording[]>([]);const[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>setItems(await listRecordings()),[]);useFocusEffect(useCallback(()=>{load()},[load]));const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};return <View style={s.root}><FlatList data={items} keyExtractor={x=>x.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} ListEmptyComponent={<View style={s.empty}><Text style={s.emptyTitle}>No recordings yet</Text><Text style={s.emptyText}>Your finished recordings will appear here.</Text></View>} renderItem={({item})=><Pressable style={s.card} onPress={()=>router.push(`/recording/${item.id}`)}><View style={{flex:1}}><Text style={s.title}>{item.title}</Text><Text style={s.meta}>{new Date(item.createdAt).toLocaleDateString()} • {duration(item.durationMs)} • {item.segmentUris.length} segment{item.segmentUris.length===1?'':'s'}</Text><Text style={s.status}>{item.notes?'PDF READY':item.transcript?'TRANSCRIBED':'RECORDED'}</Text></View><Text style={s.arrow}>›</Text></Pressable>}/></View>}
const s=StyleSheet.create({root:{flex:1,padding:18},card:{backgroundColor:'#fff',padding:18,borderRadius:18,marginBottom:12,flexDirection:'row',alignItems:'center'},title:{fontSize:16,fontWeight:'800',color:'#0B1736'},meta:{fontSize:12,color:'#697386',marginTop:5},status:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#6341E8',marginTop:9},arrow:{fontSize:34,color:'#8993A8'},empty:{alignItems:'center',paddingTop:80},emptyTitle:{fontSize:20,fontWeight:'900',color:'#0B1736'},emptyText:{color:'#667085',marginTop:8}});
